apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.hello-neuvector.cattle-neuvector-system
  namespace: cattle-neuvector-system
spec:
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.hello-neuvector.hello-neuvector-ingress-0
    ports: any
    priority: 0
    selector:
      comment: ""
      name: Workload:ingress
      original_name: ""
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: rancher-demo
    path: /bin/rancher-demo
  process_profile:
    baseline: default
  target:
    policymode: Protect
    selector:
      comment: ""
      criteria:
      - key: service
        op: =
        value: hello-neuvector.cattle-neuvector-system
      - key: domain
        op: =
        value: hello-neuvector
      name: nv.hello-neuvector.cattle-neuvector-system
      original_name: ""
  waf:
    settings: []
    status: true
